"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const cliente_1 = __importDefault(require("../modelos/cliente"));
const endereco_1 = __importDefault(require("../modelos/endereco"));
const telefone_1 = __importDefault(require("../modelos/telefone"));
let cliente = new cliente_1.default();
cliente.nome = "Antoine de Saint-Exupéry";
cliente.nomeSocial = ``;
cliente.dataCadastro = new Date(1943, 11, 21);
cliente.dataNascimento = new Date(1900, 6, 29);
let endereco = new endereco_1.default();
endereco.rua = `R. das Roseiras`;
endereco.bairro = ``;
endereco.cidade = `Tamanrasset`;
endereco.estado = `Província de Tamanrasset`;
endereco.pais = `Argélia`;
endereco.codigoPostal = `11000`;
cliente.endereco = endereco;
let telefone = new telefone_1.default("12", "12345-6789");
cliente.telefones.push(telefone);
let dependente = new cliente_1.default();
dependente.nome = `Beauvoir de Saint-Exupéry`;
dependente.nomeSocial = `O Pequeno Príncipe`;
dependente.dataCadastro = new Date(1943, 11, 21);
dependente.dataNascimento = new Date(1943, 10, 6);
dependente.endereco = cliente.endereco.clonar();
dependente.endereco = cliente.endereco.clonar();
dependente.telefones = cliente.telefones.map(tel => tel.clonar());
dependente.titular = cliente;
cliente.dependentes.push(dependente);
console.log(cliente);
console.log(dependente);
